// Package push sends Web Push messages — the notification a phone shows when
// the app isn't open. It is hand-rolled over the standard library, like the rest
// of Malten's clients, so the binary keeps no external dependencies.
//
// Two specs are involved, and both are implemented here:
//
//   - RFC 8292 (VAPID): the server identifies itself to the push service with a
//     signed JWT (ES256) and its public key.
//   - RFC 8291 (Message Encryption): the payload is encrypted end-to-end for the
//     subscriber's browser with a key only that browser holds. The push service
//     (Google, Apple, Mozilla) relays ciphertext it cannot read.
package push

import (
	"bytes"
	"crypto/aes"
	"crypto/cipher"
	"crypto/ecdh"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/hkdf"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
	"math/big"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"time"
)

// Subscription is what the browser hands over from PushManager.subscribe().
type Subscription struct {
	Endpoint string `json:"endpoint"`
	Keys     struct {
		P256dh string `json:"p256dh"` // the browser's public key (base64url, uncompressed point)
		Auth   string `json:"auth"`   // 16-byte shared authentication secret (base64url)
	} `json:"keys"`
}

// Sender holds the application's VAPID identity. One per server.
type Sender struct {
	priv    *ecdsa.PrivateKey
	subject string // mailto: or https: URL identifying the operator
	HTTP    *http.Client
}

var b64 = base64.RawURLEncoding

// NewSender builds a sender from a VAPID private key (base64url-encoded raw
// P-256 scalar, as generated by GenerateKey).
func NewSender(privateKey, subject string) (*Sender, error) {
	raw, err := b64.DecodeString(strings.TrimSpace(privateKey))
	if err != nil {
		return nil, fmt.Errorf("vapid key is not base64url: %w", err)
	}
	if len(raw) != 32 {
		return nil, fmt.Errorf("vapid key is %d bytes, want 32", len(raw))
	}
	d := new(big.Int).SetBytes(raw)
	x, y := elliptic.P256().ScalarBaseMult(raw)
	priv := &ecdsa.PrivateKey{D: d, PublicKey: ecdsa.PublicKey{Curve: elliptic.P256(), X: x, Y: y}}
	if subject == "" {
		subject = "https://malten.ai"
	}
	return &Sender{priv: priv, subject: subject, HTTP: &http.Client{Timeout: 15 * time.Second}}, nil
}

// GenerateKey makes a new VAPID keypair, both base64url-encoded: the private
// scalar (keep it server-side) and the uncompressed public point (safe to hand
// to the browser, which needs it to subscribe).
func GenerateKey() (private, public string, err error) {
	k, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return "", "", err
	}
	d := make([]byte, 32)
	k.D.FillBytes(d)
	return b64.EncodeToString(d), b64.EncodeToString(elliptic.Marshal(elliptic.P256(), k.X, k.Y)), nil
}

// PublicKey is the application server key the browser subscribes with.
func (s *Sender) PublicKey() string {
	return b64.EncodeToString(elliptic.Marshal(elliptic.P256(), s.priv.PublicKey.X, s.priv.PublicKey.Y))
}

// ErrGone means the subscription is dead (the browser unsubscribed, or the app
// was removed). The caller should forget it.
var ErrGone = fmt.Errorf("push subscription is gone")

// Send delivers an encrypted payload to one subscription. ttl is how long the
// push service should hold the message if the device is offline.
func (s *Sender) Send(sub Subscription, payload []byte, ttl time.Duration) error {
	body, err := encrypt(sub, payload)
	if err != nil {
		return err
	}
	auth, err := s.authorization(sub.Endpoint)
	if err != nil {
		return err
	}
	req, err := http.NewRequest(http.MethodPost, sub.Endpoint, bytes.NewReader(body))
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", auth)
	req.Header.Set("Content-Encoding", "aes128gcm")
	req.Header.Set("Content-Type", "application/octet-stream")
	req.Header.Set("TTL", strconv.Itoa(int(ttl.Seconds())))
	req.Header.Set("Urgency", "normal")

	resp, err := s.HTTP.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	_, _ = io.Copy(io.Discard, io.LimitReader(resp.Body, 4<<10))
	switch {
	case resp.StatusCode == http.StatusNotFound || resp.StatusCode == http.StatusGone:
		return ErrGone
	case resp.StatusCode >= 300:
		return fmt.Errorf("push service returned %d", resp.StatusCode)
	}
	return nil
}

// authorization builds the VAPID header: a JWT for the push service's origin,
// signed with the application key, plus that key.
func (s *Sender) authorization(endpoint string) (string, error) {
	u, err := url.Parse(endpoint)
	if err != nil {
		return "", err
	}
	header := b64.EncodeToString([]byte(`{"typ":"JWT","alg":"ES256"}`))
	claims, err := json.Marshal(map[string]any{
		"aud": u.Scheme + "://" + u.Host,
		"exp": time.Now().Add(12 * time.Hour).Unix(),
		"sub": s.subject,
	})
	if err != nil {
		return "", err
	}
	signing := header + "." + b64.EncodeToString(claims)
	sum := sha256.Sum256([]byte(signing))
	r, sig, err := ecdsa.Sign(rand.Reader, s.priv, sum[:])
	if err != nil {
		return "", err
	}
	// JWS wants the raw 64-byte r||s, not ASN.1.
	out := make([]byte, 64)
	r.FillBytes(out[:32])
	sig.FillBytes(out[32:])
	return "vapid t=" + signing + "." + b64.EncodeToString(out) + ", k=" + s.PublicKey(), nil
}

// encrypt implements RFC 8291: derive a key from an ephemeral ECDH exchange with
// the browser's public key, then seal the payload as a single aes128gcm record.
func encrypt(sub Subscription, payload []byte) ([]byte, error) {
	uaBytes, err := b64.DecodeString(sub.Keys.P256dh)
	if err != nil {
		return nil, fmt.Errorf("bad p256dh: %w", err)
	}
	authSecret, err := b64.DecodeString(sub.Keys.Auth)
	if err != nil {
		return nil, fmt.Errorf("bad auth secret: %w", err)
	}
	ua, err := ecdh.P256().NewPublicKey(uaBytes)
	if err != nil {
		return nil, fmt.Errorf("bad subscriber key: %w", err)
	}
	as, err := ecdh.P256().GenerateKey(rand.Reader)
	if err != nil {
		return nil, err
	}
	shared, err := as.ECDH(ua)
	if err != nil {
		return nil, err
	}
	asBytes := as.PublicKey().Bytes()

	// The "key info" binds the derived key to both parties' public keys, so a
	// message can only be read by the browser it was sealed for.
	info := append([]byte("WebPush: info\x00"), uaBytes...)
	info = append(info, asBytes...)
	ikm, err := hkdf.Key(sha256.New, shared, authSecret, string(info), 32)
	if err != nil {
		return nil, err
	}

	salt := make([]byte, 16)
	if _, err := rand.Read(salt); err != nil {
		return nil, err
	}
	cek, err := hkdf.Key(sha256.New, ikm, salt, "Content-Encoding: aes128gcm\x00", 16)
	if err != nil {
		return nil, err
	}
	nonce, err := hkdf.Key(sha256.New, ikm, salt, "Content-Encoding: nonce\x00", 12)
	if err != nil {
		return nil, err
	}

	block, err := aes.NewCipher(cek)
	if err != nil {
		return nil, err
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, err
	}
	// A single record: the payload followed by the 0x02 "last record" delimiter.
	plain := append(append([]byte{}, payload...), 0x02)
	sealed := gcm.Seal(nil, nonce, plain, nil)

	// aes128gcm content-coding header: salt | record size | key id length | key id.
	var out bytes.Buffer
	out.Write(salt)
	_ = binary.Write(&out, binary.BigEndian, uint32(4096))
	out.WriteByte(byte(len(asBytes)))
	out.Write(asBytes)
	out.Write(sealed)
	return out.Bytes(), nil
}
