const {readFileSync}=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const {webcrypto}=require('node:crypto');
const elements=new Map();
function element(){const e={focus(){this.focused=true},children:[],value:'',style:{},elements:[],classList:{add(){},remove(){}},setAttribute(){},addEventListener(){},append(...v){this.children.push(...v)},appendChild(v){this.children.push(v)},replaceChildren(){this.children=[]},removeAttribute(){}};let text='';Object.defineProperty(e,'textContent',{get(){return text+this.children.map(c=>c.textContent||'').join('')},set(v){text=v;this.children=[]}});return e;}
const document={getElementById(id){if(!elements.has(id))elements.set(id,element());return elements.get(id)},createElement:element,createTextNode:t=>({textContent:t})};
const data={points:[{id:'private',text:'old private thought',created_at:1}]};
const listeners={},window={location:{hash:'#x'},confirm:()=>true,addEventListener(name,fn){listeners[name]=fn}};
window.history={replaceState(_state,_title,url){assert.equal(url,'/');window.location.hash='';}};
let streamTimezone='';
let sent,fail=false,offline=false,unavailable=false,hold=null,lastURL='';
const pending=new Map();
const outbox={list:async()=>structuredClone([...pending.values()]),put:async p=>pending.set(p.id,structuredClone(p)),remove:async id=>pending.delete(id)};
const shared=[{id:'before-arrival',stream:'x',text:'old',created_at:Date.now()-2*60*60*1000}];
const storage=new Map();
const context={document,window,navigator:{},URL,Intl,Date,Uint8Array,crypto:webcrypto,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},setInterval(){},setTimeout,clearTimeout,AbortController,Malten:{getNetwork:()=>data,outbox},fetch:async(url,opts)=>{
 lastURL=url;
 if(!opts.method)streamTimezone=opts.headers['X-Timezone'];
 if(offline)throw new Error('offline');
 if(opts.method==='POST'){sent=JSON.parse(opts.body);if(unavailable)return {ok:false,status:503};if(hold)await hold;if(!fail)shared.push({id:String(shared.length),...sent,created_at:Date.now(),mine:true});return {ok:!fail,status:fail?422:201,text:async()=> 'capture not suitable for sharing'};}
 return {ok:true,json:async()=>shared.filter(p=>p.stream===decodeURIComponent(url.split('=')[1].split('&')[0]) && p.created_at>Number(new URL(url,'https://malten.test').searchParams.get('last')))};
}};
const source=readFileSync('server/web/page-map.html','utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
// Exercise formatting without interpreting submitted HTML or unsafe link schemes.
const formatContext={document,window,URL};
vm.runInNewContext(source.slice(source.indexOf('  function appendText('),source.indexOf('  function render()')),formatContext);
const formatted=element();
formatContext.appendText(formatted,'**Small title** *quiet* [Source](https://example.com/a) https://example.org/long/path #london <img src=x onerror=alert(1)> [bad](javascript:alert(1))');
assert(formatted.textContent.includes('Small title quiet Source example.org #london'));
assert(formatted.textContent.includes('<img src=x onerror=alert(1)>'),'HTML remains literal text');
assert(formatted.textContent.includes('[bad](javascript:alert(1))'),'unsafe Markdown is not linked');
const links=formatted.children.filter(c=>c.href);
assert.equal(links.length,3);
assert.equal(links[0].href,'https://example.com/a');
assert.equal(links[2].href,'/#london');
const credentials=element();formatContext.appendText(credentials,'https://user:password@example.com');
assert(!credentials.children.some(c=>c.href),'credential URLs are not linked');
(async()=>{
 vm.runInNewContext(source.replace('{{.AgentStreams}}',JSON.stringify([{Tag:'scheduled',Start:0,End:24}])),context);await new Promise(setImmediate);
 assert.equal(elements.get('stream').children.length,0,'private captures must not be public');
 assert(lastURL.startsWith('/api/posts?'),'keeps the posts endpoint');
 const joined=Number(new URL(lastURL,'https://malten.test').searchParams.get('last'));
 assert(Math.abs(Date.now()-joined-3600000)<1000,'arrival starts one hour ago');
 assert(!lastURL.includes('seed='),'posts are not inserted from another stream');
 let release;hold=new Promise(resolve=>{release=resolve});
 elements.get('thought').value='a reflection';
 await elements.get('composer').onsubmit({preventDefault(){}});
 assert.equal(elements.get('thought').value,'');
 assert.equal(elements.get('stream').children.length,1,'pending message appears immediately');
 elements.get('thought').value='another thought';
 await elements.get('composer').onsubmit({preventDefault(){}});
 assert.equal(elements.get('stream').children.length,2,'can post again during moderation');
 assert.equal(sent.text,'a reflection','requests are processed in order');
 elements.get('drafts').onclick();
 assert.equal(elements.get('stream').children.length,2,'sending posts appear in Drafts');
 elements.get('thought').value='still typing';
 release();hold=null;await new Promise(setImmediate);
 assert.equal(sent.stream,'x');assert.equal(sent.text,'another thought');
 assert.equal(sent.location,undefined);assert.equal(sent.agent,undefined);
 assert.equal(data.points.length,1,'old data untouched');
 assert.equal(shared.length,3);
 assert.equal(elements.get('stream').children.length,0,'sent posts leave Drafts');
 assert.equal(elements.get('drafts-empty').hidden,false,'empty Drafts is explicit');
 elements.get('all').onclick();
 assert.equal(elements.get('stream').children.length,2,'no duplicate after approval');
 assert.equal(elements.get('thought').value,'still typing','completion does not erase next draft');
 fail=true;elements.get('thought').value='keep this failed thought';
 await elements.get('composer').onsubmit({preventDefault(){}});await new Promise(setImmediate);
 assert.equal(elements.get('thought').value,'');
 assert.equal(elements.get('stream').children.length,3,'failure stays in own stream');
 const failed=elements.get('stream').children.find(p=>p.children.some(c=>(c.textContent||'').includes('Not shared')));
 assert(failed,'failure status is attached to the message');
 assert(failed.children.some(c=>(c.textContent||'').includes('capture not suitable for sharing')));
 // Offline posts survive reload, preserving both their photo and target stream.
 fail=false;offline=true;
 elements.get('thought').value='a moment without signal';
 await elements.get('composer').onsubmit({preventDefault(){}});await new Promise(setImmediate);
 assert.equal(elements.get('thought').value,'');
 assert([...pending.values()].some(p=>p.text==='a moment without signal'));
 const queued=[...pending.values()].find(p=>p.text==='a moment without signal');
 queued.photo='data:image/jpeg;base64,saved-photo';await outbox.put(queued);
 vm.runInNewContext(source,context);await new Promise(setImmediate);
 assert.equal(elements.get('stream').children.length,2,'saved outbox returns after reload while offline');
 window.location.hash='#elsewhere';listeners.hashchange();
 elements.get('drafts').onclick();
 assert.equal(elements.get('stream').children.length,2,'Drafts includes pending and rejected captures across streams');
 window.location.hash='#x';listeners.hashchange();elements.get('drafts').onclick();
 offline=false;unavailable=true;listeners.online();await new Promise(setImmediate);
 assert(pending.has(queued.id),'service failure remains queued');
 unavailable=false;listeners.online();await new Promise(setImmediate);
 assert.equal(sent.photo,queued.photo,'photo survives reload and retries');
 assert(![...pending.values()].some(p=>p.text==='a moment without signal'),'reconnect drains saved queue');
 assert.equal(shared.filter(p=>p.text==='a moment without signal').length,1);
 assert.equal(elements.get('stream').children.length,1,'only rejected draft remains after reconnect');
 elements.get('all').onclick();
 // Storage failure must preserve the composer and must never send the capture.
 const put=outbox.put;outbox.put=async()=>{throw new Error('quota');};
 elements.get('thought').value='keep draft when disk is full';
 await elements.get('composer').onsubmit({preventDefault(){}});
 assert.equal(elements.get('thought').value,'keep draft when disk is full');
 assert(!shared.some(p=>p.text==='keep draft when disk is full'));outbox.put=put;
 window.location.hash='#elsewhere';listeners.hashchange();await new Promise(setImmediate);
 assert.equal(elements.get('stream').children.length,0,'local captures stay in their original stream');
 window.location.hash='#x';listeners.hashchange();await new Promise(setImmediate);
 assert.equal(elements.get('stream').children.length,4);
 window.location.hash='#%';listeners.hashchange();await new Promise(setImmediate);
 assert(source.includes('for(let i=0;i<e.results.length;i++)'),'voice retains finalized segments');
 assert(!source.includes('geolocation'),'location permission is never requested');
 window.location.hash='#nyc';listeners.hashchange();await new Promise(setImmediate);
 assert.equal(streamTimezone,undefined,'server resolves city time without a client clock');
 // Home is automatically selected and remains stable for a timezone.
 window.location.hash='';elements.get('home').onclick({preventDefault(){}});await new Promise(setImmediate);
 const home='home';
 assert(lastURL.includes('stream=home&last='),'root loads shared home');
 assert.equal(elements.get('current-stream').textContent,'Home');

 fail=false;elements.get('thought').value='in my timezone';
 await elements.get('composer').onsubmit({preventDefault(){}});await new Promise(setImmediate);
 assert.equal(sent.stream,home,'home posts belong to the timezone');
 window.location.hash='#city';listeners.hashchange();await new Promise(setImmediate);
 elements.get('home').onclick({preventDefault(){}});await new Promise(setImmediate);
 assert(lastURL.includes('stream='+home+'&last='),'brand returns from a hashtag to timezone');
 elements.get('drafts').onclick();
 assert.equal(elements.get('stream').children.length,1,'failed draft accessible from Home');
 assert(!source.includes('getNetwork'),'legacy captures are no longer read');
 assert(!source.includes("$('saved')"),'legacy navigation removed');
 window.location.hash='#elsewhere';
 elements.get('home-link').onclick({preventDefault(){}});await new Promise(setImmediate);
 assert.equal(window.location.hash,'','visible home link uses clean root');
 assert.equal(elements.get('current-stream').textContent,'Home');
 assert.equal(elements.get('stream').children.length,1,'visible home link leaves Drafts for public Home');
 elements.get('new-stream').onclick();
 const random=window.location.hash.replace(/^#/, '');
 assert(/^[a-z0-9]{10}$/.test(random)&&/[0-9]/.test(random),'new stream has a short alphanumeric name');
 window.location.hash='#'+random;listeners.hashchange();await new Promise(setImmediate);
 assert.equal(elements.get('current-stream').textContent,random,'current stream is labelled');
 assert(elements.get('thought').focused,'new stream is ready for capture');
 elements.get('thought').value='a thought in a fresh stream';
 await elements.get('composer').onsubmit({preventDefault(){}});await new Promise(setImmediate);
 assert.equal(sent.stream,random,'capture belongs to the new stream');
 elements.get('new-stream').onclick();assert.notEqual(window.location.hash.replace(/^#/,''),random,'each new stream is distinct');
 elements.get('home-link').onclick({preventDefault(){}});await new Promise(setImmediate);
 for(const [zone,expected] of [['Europe/London','europe-london'],['America/Los_Angeles','america-los-angeles'],['Etc/GMT+5','etc-gmt-plus-5']]){
   const testWindow={...window,location:{hash:''}};
   function DateTimeFormat(...args){return args.length?new Intl.DateTimeFormat(...args):{resolvedOptions:()=>({timeZone:zone})};}
   vm.runInNewContext(source.replace('{{.AgentStreams}}','[]'),{...context,window:testWindow,Intl:{DateTimeFormat}});
   await new Promise(setImmediate);
   assert(lastURL.includes('stream=home&last='),'shared home arrival: '+zone);
   assert(!source.includes('X-Timezone'),'navigation no longer exposes timezone identifiers');
 }

 console.log('Queued posting, moderation outcomes, stream isolation and private migration: passed');
})().catch(err=>{console.error(err);process.exitCode=1;});
